yahoo:
  source:
    format: cloudFiles
    schema: yahoo
    options:
      cloudFiles.format: parquet
      cloudFiles.inferColumnTypes: true
      cloudFiles.schemaEvolutionMode: addNewColumns
  sink:
    layer: bronze
    partitionBy:
      - _ingested_at

fred:
  source:
    format: cloudFiles
    schema: fred
    options:
      cloudFiles.format: json
      cloudFiles.inferColumnTypes: true
      cloudFiles.schemaEvolutionMode: addNewColumns
  sink:
    layer: bronze
    partitionBy:
      - _ingested_at

eurostat:
  source:
    format: cloudFiles
    schema: eurostat
    options:
      cloudFiles.format: json
      cloudFiles.inferColumnTypes: true
      cloudFiles.schemaEvolutionMode: addNewColumns
  sink:
    layer: bronze
    partitionBy:
      - _ingested_at


finnhub:
  source:
    format: kafka
    schema: finnhub
    options:
      subscribe: finnhub
      startingOffsets: earliest
  sink:
    layer: bronze
    partitionBy:
      - _ingested_at