
fact_market_intraday:
  source:
    - macroeconomy_silver.finnhub_trades
  options:
    watermark: "2 minutes"
  sink:
    run_mode: streaming
    partitionBy:
      - year
      - month
      - day
    target_table: "fact_market_intraday"

fact_market_daily:
  source:
    - macroeconomy_silver.yahoo_NVDA
    - macroeconomy_silver.yahoo_ASML
    - macroeconomy_silver.yahoo_NDX
  options:
    symbols:
      - NVDA
      - ASML.AS
      - ^NDX
  sink:
    partitionBy:
      - year
      - month
      - day
    target_table: "fact_market_daily"