yahoo:
  datasets:
    - AAPL
    - MSFT
    - NVDA
  interval: 1d

fred:
  datasets:
    - FEDFUNDS
    - CPIAUCSL

eurostat:
  datasets:
    - prc_hicp_midx


finnhub:
  datasets:
    - NVDA
    - AMD
    - MSFT
    - AAPL
    - AMZN