yahoo:
  source:
    format: cloudFiles
    schema: yahoo
    options:
      cloudFiles.format: parquet
      cloudFiles.inferColumnTypes: true
      cloudFiles.schemaEvolutionMode: addNewColumns
  sinks:
    bronze:
      run_mode: available_now
      partitionBy:
        - _ingested_at
    silver:
      run_mode: batch
      partitionBy:
        - year
        - month
        - day

fred:
  source:
    format: cloudFiles
    schema: fred
    options:
      cloudFiles.format: json
      cloudFiles.inferColumnTypes: true
      cloudFiles.schemaEvolutionMode: addNewColumns
  sinks:
    bronze:
      run_mode: available_now
      partitionBy:
        - _ingested_at
    silver:
      run_mode: batch
      partitionBy:
        - year
        - month
        - day

eurostat:
  source:
    format: cloudFiles
    schema: eurostat
    options:
      cloudFiles.format: json
      cloudFiles.inferColumnTypes: true
      cloudFiles.schemaEvolutionMode: addNewColumns
  sinks:
    bronze:
      run_mode: available_now
      partitionBy:
        - _ingested_at
    silver:
      run_mode: batch
      partitionBy:
        - year
        - month
        - day

finnhub:
  source:
    format: kafka
    schema: finnhub
    options:
      subscribe: finnhub_trades
      startingOffsets: earliest
    key_format: "string"
    value_format: "json"
    json_schema: "struct<type:string,data:array<struct<c:array<string>,p:double,s:string,t:bigint,v:bigint>>>"
  sinks:
    bronze:
      run_mode: streaming
      partitionBy:
        - _ingested_at
    silver:
      run_mode: streaming
      partitionBy:
        - year
        - month
        - day