yahoo:
  datasource: yahoo
  source:
    format: cloudFiles
    schema: yahoo
    options:
      cloudFiles.format: parquet
      cloudFiles.inferColumnTypes: true
      cloudFiles.schemaEvolutionMode: addNewColumns
  datasets:
    - AAPL
    - MSFT
    - NVDA
  sink:
    layer: bronze
    partitionBy:
      - _ingested_at
  interval: 1d

fred:
  datasource: fred
  source:
    format: cloudFiles
    schema: fred
    options:
      cloudFiles.format: json
      cloudFiles.inferColumnTypes: true
      cloudFiles.schemaEvolutionMode: addNewColumns
  sink:
    layer: bronze
    partitionBy:
      - _ingested_at
  datasets:
    - FEDFUNDS
    - CPIAUCSL

eurostat:
  datasource: eurostat
  source:
    format: cloudFiles
    schema: eurostat
    options:
      cloudFiles.format: json
      cloudFiles.inferColumnTypes: true
      cloudFiles.schemaEvolutionMode: addNewColumns
  sink:
    layer: bronze
    partitionBy:
      - _ingested_at
  datasets:
    - prc_hicp_midx


finnhub:
  datasource: finnhub
  source:
    format: kafka
    schema: finnhub
    options:
      subscribe: finnhub
      startingOffsets: earliest
  sink:
    layer: bronze
    partitionBy:
      - _ingested_at
  datasets:
    - trades